name: Run CI tools

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Typescript
        run: npm run tsc

      - name: Prettier
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test

